services:
  ros2_devel:
    build:
      context: docker
    image: ghcr.io/northernforce/pifiles:main
    command: tail -f /dev/null
    working_dir: /workspaces/rosnfr
    volumes:
      - .:/workspaces/rosnfr
    network_mode: host
    privileged: true
  ros2_runtime:
    image: ghcr.io/northernforce/pifiles:main
    command: ros2 launch nfr_charged_up swervy.launch.py
    working_dir: /workspaces/rosnfr
    volumes:
      - .:/workspaces/rosnfr
    network_mode: host
    privileged: true